### ISSUE TITLE
Fatal error if amp could not connect to target

### ISSUE THREAD

**Issue by lyrixx** [jolicode/asynit#14]
If you write:

```php
public function testFoobar()
{
    $response = yield $this->get('http://something-is-not-reachable');
}
```

you get this:

```
✕ Argument 1 passed to Asynit\HttpClient\PromiseAdapter::reject() must be an instance of Http\Client\Exception, instance of Amp\Socket\ConnectException given, called in /PROJECT/tests/vendor/jolicode/asynit/src/HttpClient/PromiseAdapter.php on line 35
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Asynit\HttpClient\PromiseAdapter::reject() must be an instance of Http\Client\Exception, instance of Amp\Socket\ConnectException given, called in /PROJECT/tests/vendor/jolicode/asynit/src/HttpClient/PromiseAdapter.php on line 35 and defined in /PROJECT/tests/vendor/jolicode/asynit/src/HttpClient/PromiseAdapter.php:92
Stack trace:
#0 /PROJECT/tests/vendor/jolicode/asynit/src/HttpClient/PromiseAdapter.php(35): Asynit\HttpClient\PromiseAdapter->reject(Object(Amp\Socket\ConnectException))
#1 /PROJECT/tests/vendor/amphp/amp/lib/Internal/ResolutionQueue.php(51): Asynit\HttpClient\PromiseAdapter->Asynit\HttpClient\{closure}(Object(Amp\Socket\ConnectException), NULL)
#2 /PROJECT/tests/vendor/amphp/amp/lib/Failure.php(26): Amp\Internal\ResolutionQueue->__invoke(Object(Amp\Socket\ConnectException), NULL)
#3 /PROJECT/tests/vendor/amphp/amp/lib/Internal/Placeholder.php(118): Amp\Failure->onResolve(Object(Amp\Internal\ResolutionQueue))
#4 /PROJECT in /PROJECT/tests/vendor/jolicode/asynit/src/HttpClient/PromiseAdapter.php on line 92
```

**Comment by joelwurtz** [comment]
Was fix in https://github.com/jolicode/asynit/commit/aca77930fe13a6b84c8ebfcb18f7c72d831ba765 /cc @lyrixx

**Comment by joelwurtz** [comment]
Thanks for the issue
